export default function Input() {
    return(
        <input 
        type="text" 
        inputMode="numeric" 
        autoComplete="one-time-code" 
        maxLength={1} 
        className="
          bg-third-gray 
            mx-3 
            my-10 
            w-12 
            py-3 
            text-center 
            text-3xl 
            font-sansInter 
            text-primary-brown 
            font-medium 
            rounded-md
        "/>
    )
}